// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04aKtTgnAA9ppOT9b_7rpBv0sOI2Xoq0',
    appId: '1:511331520219:web:46d1337d4fe7da359706fe',
    messagingSenderId: '511331520219',
    projectId: 'globalconnect-d62f5',
    authDomain: 'globalconnect-d62f5.firebaseapp.com',
    storageBucket: 'globalconnect-d62f5.firebasestorage.app',
    measurementId: 'G-N6HR9CRC1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSmrTXY02dmhAEMgTU-VSy4zTlmKyDuQ',
    appId: '1:511331520219:android:5bd03d1537a952059706fe',
    messagingSenderId: '511331520219',
    projectId: 'globalconnect-d62f5',
    storageBucket: 'globalconnect-d62f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemdBHKAvu8rCUgAQs7HvHfVJY-eBer5Q',
    appId: '1:511331520219:ios:428dca8dc1380ce39706fe',
    messagingSenderId: '511331520219',
    projectId: 'globalconnect-d62f5',
    storageBucket: 'globalconnect-d62f5.firebasestorage.app',
    iosBundleId: 'com.example.globalConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemdBHKAvu8rCUgAQs7HvHfVJY-eBer5Q',
    appId: '1:511331520219:ios:428dca8dc1380ce39706fe',
    messagingSenderId: '511331520219',
    projectId: 'globalconnect-d62f5',
    storageBucket: 'globalconnect-d62f5.firebasestorage.app',
    iosBundleId: 'com.example.globalConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC04aKtTgnAA9ppOT9b_7rpBv0sOI2Xoq0',
    appId: '1:511331520219:web:a150559eaa0e60d39706fe',
    messagingSenderId: '511331520219',
    projectId: 'globalconnect-d62f5',
    authDomain: 'globalconnect-d62f5.firebaseapp.com',
    storageBucket: 'globalconnect-d62f5.firebasestorage.app',
    measurementId: 'G-VNYS0F6W2E',
  );
}
